apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api-app.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "api-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "api-app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "api-app.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: api-gateway
          image: "{{ .Values.apiGateway.image.repository }}:{{ .Values.apiGateway.image.tag }}"
          imagePullPolicy: {{ .Values.apiGateway.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 4000
          # Add environment variables as needed for API Gateway
          # Add readiness and liveness probes as needed

{{/* Add other deployment templates for microservices (auth-service, product-catalog, cart, and order-processing) here */}}

