apiVersion: v1
kind: Service
metadata:
  name: {{ include "e-commerce-chart.fullname" . }}-api-gateway
  labels:
    app.kubernetes.io/name: {{ include "e-commerce-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 4000
  selector:
    app.kubernetes.io/name: {{ include "e-commerce-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: api-gateway

{{- if .Values.authService.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "e-commerce-chart.fullname" . }}-auth-service
  labels:
    app.kubernetes.io/name: {{ include "e-commerce-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app.kubernetes.io/name: {{ include "e-commerce-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: auth-service
{{- end }}

{{/* Service for product-catalog */}}
{{- if .Values.productCatalog.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "e-commerce-chart.fullname" . }}-product-catalog
  labels:
    app.kubernetes.io/name: {{ include "e-commerce-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app.kubernetes.io/name: {{ include "e-commerce-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: product-catalog
{{- end }}

{{/* Service for cart */}}
{{- if .Values.cart.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "e-commerce-chart.fullname" . }}-cart
  labels:
    app.kubernetes.io/name: {{ include "e-commerce-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app.kubernetes.io/name: {{ include "e-commerce-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: cart
{{- end }}

{{/* Service for order-processing */}}
{{- if .Values.orderProcessing.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "e-commerce-chart.fullname" . }}-order-processing
  labels:
    app.kubernetes.io/name: {{ include "e-commerce-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app.kubernetes.io/name: {{ include "e-commerce-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: order-processing
{{- end }}